version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  movie-api:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      OMDB_API_KEY: ${OMDB_API_KEY}
  auth-api:
    build: ./nodejs-recruitment-task/.
    environment:
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3001:3001"
